[versions]
agp = "9.0.1"
androidSdk = "10.2.0"
circleimageview = "3.1.0"
circularimageview = "4.3.1"
eventbus = "3.3.1"
fresco = "3.6.0"
glide = "5.0.5"
gson = "2.13.2"
hiltAndroid = "2.59.1"
hivemqMqttClient = "1.3.12"
inferAnnotation = "0.18.0"
ion = "3.1.0"
jacksonAnnotations = "2.21"
jacksonDatabind = "2.21.0"
kotlin = "2.2.21"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.13.0"
activity = "1.12.4"
constraintlayout = "2.2.1"
moshi = "1.15.2"
navigationFragmentKtx = "2.9.7"
navigationUiKtx = "2.9.7"
fragment = "1.8.9"
okhttp = "5.3.2"
okio = "3.16.4"
picasso = "2.71828"
primecalendar = "1.7.0"
retrofit = "3.0.0"
roomRuntime = "2.8.4"
rxandroid = "3.0.2"
rxjava = "3.1.12"
volley = "1.2.1"

[libraries]
adapter-rxjava3 = { module = "com.squareup.retrofit2:adapter-rxjava3", version.ref = "retrofit" }
android-sdk = { module = "org.maplibre.gl:android-sdk", version.ref = "androidSdk" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomRuntime" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }
androidx-room-rxjava3 = { module = "androidx.room:room-rxjava3", version.ref = "roomRuntime" }
circleimageview = { module = "de.hdodenhof:circleimageview", version.ref = "circleimageview" }
circularimageview = { module = "com.mikhaellopez:circularimageview", version.ref = "circularimageview" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
converter-jackson = { module = "com.squareup.retrofit2:converter-jackson", version.ref = "retrofit" }
converter-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit" }
converter-scalars = { module = "com.squareup.retrofit2:converter-scalars", version.ref = "retrofit" }
eventbus = { module = "org.greenrobot:eventbus", version.ref = "eventbus" }
fresco = { module = "com.facebook.fresco:fresco", version.ref = "fresco" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroid" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hiltAndroid" }
hivemq-mqtt-client = { module = "com.hivemq:hivemq-mqtt-client", version.ref = "hivemqMqttClient" }
infer-annotation = { module = "com.facebook.infer.annotation:infer-annotation", version.ref = "inferAnnotation" }
ion = { module = "com.koushikdutta.ion:ion", version.ref = "ion" }
jackson-annotations = { module = "com.fasterxml.jackson.core:jackson-annotations", version.ref = "jacksonAnnotations" }
jackson-core = { module = "com.fasterxml.jackson.core:jackson-core", version.ref = "jacksonDatabind" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jacksonDatabind" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigationUiKtx" }
androidx-fragment = { group = "androidx.fragment", name = "fragment", version.ref = "fragment" }
moshi = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
picasso = { module = "com.squareup.picasso:picasso", version.ref = "picasso" }
primecalendar = { module = "com.aminography:primecalendar", version.ref = "primecalendar" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
rxandroid = { module = "io.reactivex.rxjava3:rxandroid", version.ref = "rxandroid" }
rxjava = { module = "io.reactivex.rxjava3:rxjava", version.ref = "rxjava" }
volley = { module = "com.android.volley:volley", version.ref = "volley" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

